#!/usr/bin/env bun
/**
 * ======================================================================
 * Sitemap Path Generator
 * ======================================================================
 * Purpose: Read cached site data from data.json and generate a sorted
 *          list of all dynamic page URLs for the sitemap.
 *
 * Input:   scripts/data.json (generated by fetch-data.ts)
 * Output:  public/paths.txt — one absolute URL per line.
 *
 * Usage:
 *   bun run generate:paths
 *
 * Dependencies:
 *   Run fetch:data first so data.json is available.
 * ======================================================================
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

import { loadSiteData } from './utils/site-data';
import type { SiteData } from './utils/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = path.resolve(__dirname, '..', 'public', 'paths.txt');

const SITE_URL = 'https://kabirdohehub.vercel.app';
const PER_PAGE = 10;

/**
 * Generate paginated page paths for a given base path and total item count.
 *
 * @param {string} basePath - The base path (e.g. /category/devotion).
 * @param {number} totalItems - Total number of items to paginate.
 *
 * @returns {string[]} Array of paginated paths (page 2+ only, page 1 is the base).
 */
function generatePaginationPaths(basePath: string, totalItems: number): string[] {
  const pages: string[] = [];
  const totalPages = Math.ceil(totalItems / PER_PAGE);

  for (let i = 2; i <= totalPages; i++) {
    pages.push(SITE_URL + basePath + '/' + i);
  }

  return pages;
}

/**
 * Generate the full list of site URLs from cached data.
 *
 * @param {SiteData} data - The cached site data.
 *
 * @returns {string[]} Sorted list of all site URLs.
 */
function generateAllUrls(data: SiteData): string[] {
  const allUrls: string[] = [];

  // 1. Static pages
  const staticPages = [
    '/',
    '/couplets',
    '/popular-couplets',
    '/featured-couplets',
    '/categories',
    '/tags',
    '/about',
    '/privacy',
    '/terms',
    '/search',
  ];

  for (const page of staticPages) {
    allUrls.push(SITE_URL + page);
  }

  // 2. Couplet detail pages
  for (const post of data.posts) {
    allUrls.push(SITE_URL + '/couplet/' + post.slug);
  }

  // 3. Category pages with pagination
  for (const cat of data.categories) {
    allUrls.push(SITE_URL + '/category/' + cat.slug);
    const paginationPaths = generatePaginationPaths('/category/' + cat.slug, cat.post_count);
    allUrls.push(...paginationPaths);
  }

  // 4. Tag pages with pagination
  for (const tag of data.tags) {
    allUrls.push(SITE_URL + '/tag/' + tag.slug);
    const paginationPaths = generatePaginationPaths('/tag/' + tag.slug, tag.post_count);
    allUrls.push(...paginationPaths);
  }

  // 5. All couplets pagination
  const coupletsPagination = generatePaginationPaths('/couplets', data.totalCount);
  allUrls.push(...coupletsPagination);

  // 6. Popular couplets pagination
  const popularPagination = generatePaginationPaths('/popular-couplets', data.popularCount);
  allUrls.push(...popularPagination);

  // 7. Featured couplets pagination
  const featuredPagination = generatePaginationPaths('/featured-couplets', data.featuredCount);
  allUrls.push(...featuredPagination);

  return allUrls;
}

/**
 * Write the sorted list of URLs to the output file.
 *
 * @param {string[]} allUrls - All site URLs.
 */
function writePathsFile(allUrls: string[]): void {
  const dir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const sorted = [...new Set(allUrls)].sort();
  fs.writeFileSync(OUTPUT_FILE, sorted.join('\n') + '\n', 'utf-8');
  console.log('Wrote ' + sorted.length + ' URLs to ' + OUTPUT_FILE);
}

/**
 * Entry point: read data.json, generate all URL paths, and write paths.txt.
 *
 * @returns {Promise<void>} Resolves when public/paths.txt has been written.
 */
async function main(): Promise<void> {
  const data = loadSiteData();

  console.log(
    'Generating paths from '
      + data.posts.length
      + ' posts, '
      + data.categories.length
      + ' categories, '
      + data.tags.length
      + ' tags...'
  );

  const allUrls = generateAllUrls(data);
  writePathsFile(allUrls);

  console.log(
    '  - '
      + data.posts.length
      + ' couplet pages, '
      + data.categories.length
      + ' categories, '
      + data.tags.length
      + ' tags'
  );
}

main().catch(function (err) {
  console.error('Script failed:', err);
  process.exit(1);
});
