/**
 * IndexNow Script
 *
 * Submits URLs from sitemap to IndexNow API for search engine indexing.
 *
 * Usage:
 *   bun run indexnow - Submit URLs to IndexNow
 */

import fs from 'fs/promises';
import path from 'path';

import ora from 'ora';
import xml2js from 'xml2js';

// The public site URL used to derive host and key location for IndexNow.
const SITE_URL = 'https://kabirdoheapi.vercel.app';
// IndexNow key (published as a verification file at SITE_URL/<KEY>.txt).
const KEY = '91c80f732f4e4e5b80b4c02a7e8c9e9c';
const KEY_LOCATION = SITE_URL + '/' + KEY + '.txt';
// Local path to the sitemap file generated by the Next.js build.
const SITEMAP_PATH = path.resolve(process.cwd(), 'public', 'sitemap-0.xml');
// Number of URLs to submit per IndexNow request (API suggests batching).
const CHUNK_SIZE = 100;

/**
 * Submits sitemap URLs to IndexNow in chunks for faster search engine indexing.
 *
 * @returns {Promise<void>} Resolves when all URL chunks have been processed.
 */
async function main(): Promise<void> {
  const spinner = ora('Reading sitemap...').start();

  // Read the sitemap file produced by the site build.
  let sitemapContent: string;
  try {
    sitemapContent = await fs.readFile(SITEMAP_PATH, 'utf8');
  } catch {
    // If sitemap is missing, fail early with an explanatory message.
    spinner.fail('Sitemap file not found: ' + SITEMAP_PATH);
    process.exit(1);
  }

  // Parse the sitemap XML into a JS object structure.
  let parsed: { urlset?: { url?: Array<{ loc?: string[] }> } };
  try {
    parsed = await xml2js.parseStringPromise(sitemapContent);
  } catch {
    // Parsing failure likely indicates a malformed sitemap file.
    spinner.fail('Failed to parse sitemap XML');
    process.exit(1);
  }

  // Extract URL strings from the parsed sitemap entries.
  const urls = parsed.urlset?.url?.map((entry) => entry.loc?.[0]).filter(Boolean) as string[] | undefined;

  if (!urls || urls.length === 0) {
    // Nothing to submit — exit gracefully.
    spinner.warn('No URLs found in sitemap');
    process.exit(0);
  }

  spinner.succeed('Found ' + urls.length + ' URLs');

  // Submit URLs in chunks to avoid overly large payloads.
  for (let i = 0; i < urls.length; i += CHUNK_SIZE) {
    const chunk = urls.slice(i, i + CHUNK_SIZE);
    spinner.start('Submitting URLs ' + (i + 1) + ' to ' + Math.min(i + CHUNK_SIZE, urls.length));

    try {
      // POST to IndexNow with the required payload fields.
      const response = await fetch('https://api.indexnow.org/indexnow', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ host: new URL(SITE_URL).host, key: KEY, keyLocation: KEY_LOCATION, urlList: chunk }),
      });

      if (response.ok) {
        spinner.succeed('Submitted ' + chunk.length + ' URLs');
      } else {
        // Capture server error text to aid debugging.
        const errorText = await response.text();
        spinner.fail('Failed: ' + errorText);
      }
    } catch (error) {
      // Network or runtime error — report and continue with remaining chunks.
      spinner.fail('Network error: ' + (error as Error).message);
    }
  }

  // Final status message.
  ora('All URLs processed!').succeed();
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
