/**
 * ======================================================================
 * Next Sitemap Configuration
 * ======================================================================
 * Purpose: Generate sitemaps and robots.txt to help search engines
 *          discover and index site content.
 *          Use `npx next-sitemap` for local testing.
 *
 *          Dynamic page paths are generated by `scripts/generate-paths.ts`
 *          and written to `public/paths.txt`.
 * Docs:    https://github.com/iamvishnusankar/next-sitemap
 * ======================================================================
 */

const fs = require('fs');
const path = require('path');

const { createSitemapConfig } = require('@vijayhardaha/dev-config/next-sitemap');

const siteDomain = 'https://kabirdohehub.vercel.app';

/** @type {import('next-sitemap').IConfig} */
const baseConfig = createSitemapConfig({
  siteUrl: siteDomain,
  outDir: process.env.NODE_ENV === 'production' ? '/vercel/output/static' : './public',
});

/**
 * Generate a sitemap entry with default changefreq, priority, and lastmod.
 *
 * @param {string} loc - The absolute URL path.
 *
 * @returns {import('next-sitemap').ISitemapField} A sitemap entry object.
 */
function sitemapEntry(loc) {
  const lastmod = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  return { loc, changefreq: 'weekly', priority: 0.7, lastmod };
}

/**
 * Read additional paths from public/paths.txt (generated by
 * `scripts/generate-paths.ts`).
 *
 * Each line should be a full absolute URL. Lines that do not start with the
 * site domain are skipped.
 *
 * @returns {string[]} Array of validated absolute URLs.
 */
function readPathsFile() {
  const pathsFile = path.resolve(process.cwd(), 'public', 'paths.txt');

  if (!fs.existsSync(pathsFile)) {
    console.warn('⚠️  public/paths.txt not found. Run `bun run generate:paths` first.');
    return [];
  }

  const content = fs.readFileSync(pathsFile, 'utf-8');
  const lines = content
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

  // Only keep URLs that start with the site domain
  const validPaths = lines.filter((line) => line.startsWith(siteDomain));

  const skipped = lines.length - validPaths.length;
  if (skipped > 0) {
    console.warn(`⚠️  Skipped ${skipped} invalid path(s) in public/paths.txt.`);
  }

  return validPaths;
}

/**
 * Additional paths to include in the sitemap that the crawler may not
 * discover automatically (e.g., dynamic couplet pages, paginated listings).
 *
 * Paths are read from public/paths.txt if the file exists.
 */
const additionalPaths = [...readPathsFile().map((loc) => sitemapEntry(loc))];

/** @type {import('next-sitemap').IConfig} */
const config = { ...baseConfig, ...{ additionalPaths: async () => additionalPaths }, sitemapSize: 100 };

module.exports = config;
